apiVersion: v1
kind: Service
metadata:
  name: seonology-journey-back
  namespace: seonology-journey
  labels:
    app.kubernetes.io/name: seonology-journey-back
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seonology-journey-back
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
    - name: metrics
      port: 9091
      targetPort: metrics
