apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - back-deployment.yaml
  - back-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-ingressroute.yaml
  - api-ingressroute.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: seonology-journey
    includeSelectors: false
    includeTemplates: false
