apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seonology-journey

resources:
  - ../../base

# Image tag は ArgoCD Image Updater もしくは CI で書き換え
images:
  - name: ghcr.io/seonnoh/seonology-journey-back
    newTag: latest
  - name: ghcr.io/seonnoh/seonology-journey-api
    newTag: latest
  - name: ghcr.io/seonnoh/seonology-journey-web
    newTag: latest
